[colors]
foreground = "#4c545d"
background = "#c9d2dd"
cursor_bg = "#4c545d"
cursor_border = "#4c545d"
cursor_fg = "#c9d2dd"
selection_bg = "#afb8cc"
selection_fg = "#4c545d"
split = "#007496"
compose_cursor = "#ae5d00"
scrollbar_thumb = "#c0c6d3"

ansi = ["#a1a8b1", "#f62466", "#00663d", "#7d5a00", "#007496", "#7e58ff", "#006b77", "#6172b0"]
brights = ["#a1a6c5", "#c81d47", "#006252", "#615724", "#0074ba", "#bb00a0", "#006263", "#4c545d"]

[colors.tab_bar]
inactive_tab_edge = "#d8dfe7"
background = "#c9d2dd"

[colors.tab_bar.active_tab]
fg_color = "#d8dfe7"
bg_color = "#007496"

[colors.tab_bar.inactive_tab]
fg_color = "#8990b3"
bg_color = "#c0c6d3"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#007496"
bg_color = "#c0c6d3"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#007496"
bg_color = "#c9d2dd"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#007496"
bg_color = "#c9d2dd"

[metadata]
aliases = []
author = "folke & serhez"
name = "teide_light"