[colors]
foreground = "#E7EAEE"
background = "#22282F"
cursor_bg = "#E7EAEE"
cursor_border = "#E7EAEE"
cursor_fg = "#22282F"
selection_bg = "#363d4f"
selection_fg = "#E7EAEE"
split = "#5CCEFF"
compose_cursor = "#FFA75A"
scrollbar_thumb = "#2C313A"

ansi = ["#1b2026", "#F97791", "#38FFA5", "#F7D96C", "#5CCEFF", "#AE9EFF", "#0AE7FF", "#a9b1d6"]
brights = ["#414868", "#F5335A", "#86EACF", "#FFDB70", "#9BEAFD", "#FFAFEB", "#00FBFF", "#E7EAEE"]

[colors.tab_bar]
inactive_tab_edge = "#1a1e23"
background = "#22282F"

[colors.tab_bar.active_tab]
fg_color = "#1a1e23"
bg_color = "#5CCEFF"

[colors.tab_bar.inactive_tab]
fg_color = "#545c7e"
bg_color = "#2C313A"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#5CCEFF"
bg_color = "#2C313A"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#5CCEFF"
bg_color = "#22282F"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#5CCEFF"
bg_color = "#22282F"

[metadata]
aliases = []
author = "folke"
name = "teide_dimmed"