# -----------------------------------------------------------------------------
# Teide Alacritty Colors
# Theme: Teide Dimmed
# Upstream: https://github.com/serhez/teide.nvim/raw/main/extras/alacritty/teide_dimmed.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#232930'
foreground = '#E7EAEE'

# Normal colors
[colors.normal]
black = '#1c2126'
red = '#F97791'
green = '#38FFA5'
yellow = '#FFA064'
blue = '#5CCEFF'
magenta = '#B1A2FF'
cyan = '#0AE7FF'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#F73F64'
green = '#41FFDC'
yellow = '#FFE77A'
blue = '#89BEFF'
magenta = '#FFB3EC'
cyan = '#00FBFF'
white = '#E7EAEE'
