# -----------------------------------------------------------------------------
# Teide Alacritty Colors
# Theme: Teide Dimmed
# Upstream: https://github.com/folke/teide.nvim/raw/main/extras/alacritty/teide_dimmed.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#22282F'
foreground = '#E7EAEE'

#[colors.cursor]
#cursor = '#E7EAEE'
#text = '#22282F'

# Normal colors
[colors.normal]
black = '#1b2026'
red = '#F97791'
green = '#38FFA5'
yellow = '#F7D96C'
blue = '#5CCEFF'
magenta = '#AE9EFF'
cyan = '#0AE7FF'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#F5335A'
green = '#86EACF'
yellow = '#FFDB70'
blue = '#9BEAFD'
magenta = '#FFAFEB'
cyan = '#00FBFF'
white = '#E7EAEE'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#FFA75A'

[[colors.indexed_colors]]
index = 17
color = '#F5335A'

