# -----------------------------------------------------------------------------
# Teide Alacritty Colors
# Theme: Teide Light
# Upstream: https://github.com/serhez/teide.nvim/raw/main/extras/alacritty/teide_light.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#c9d2dd'
foreground = '#4c545d'

# Normal colors
[colors.normal]
black = '#a1a8b1'
red = '#f62466'
green = '#00663d'
yellow = '#7d5a00'
blue = '#007496'
magenta = '#7e58ff'
cyan = '#006b77'
white = '#6172b0'

# Bright colors
[colors.bright]
black = '#a1a6c5'
red = '#c81d47'
green = '#006252'
yellow = '#615724'
blue = '#0074ba'
magenta = '#bb00a0'
cyan = '#006263'
white = '#4c545d'
