[[themes]]
name = "Teide Light"
[themes.palette]
background = "#ebedf1"
foreground = "#6172b0"
black = "#a1a6c5"
red = "#f62466"
green = "#00663d"
yellow = "#6c5800"
blue = "#007496"
magenta = "#be00a2"
cyan = "#006b77"
white = "${white}"
bright_black = "#e0e4ea"
bright_red = "#ce2348"
bright_green = "#376659"
bright_yellow = "#a25f00"
bright_blue = "#0075bd"
bright_magenta = "#805bff"
bright_cyan = "#13658a"
bright_white = "#4c545d"
