[[themes]]
name = "Teide Dimmed"
[themes.palette]
background = "#1a1f24"
foreground = "#a9b1d6"
black = "#414868"
red = "#F97791"
green = "#38FFA5"
yellow = "#FFE26C"
blue = "#5CCEFF"
magenta = "#FFAFEB"
cyan = "#0AE7FF"
white = "${white}"
bright_black = "#232930"
bright_red = "#F73B61"
bright_green = "#86EACF"
bright_yellow = "#FF9858"
bright_blue = "#89BEFF"
bright_magenta = "#B0A0FF"
bright_cyan = "#AFDBFD"
bright_white = "#E7EAEE"
