[[themes]]
name = "Teide Dimmed"
[themes.palette]
background = "#1a1e23"
foreground = "#a9b1d6"
black = "#414868"
red = "#F97791"
green = "#38FFA5"
yellow = "#FFDB70"
blue = "#5CCEFF"
magenta = "#FFAFEB"
cyan = "#0AE7FF"
white = "${white}"
bright_black = "#22282F"
bright_red = "#F5335A"
bright_green = "#86EACF"
bright_yellow = "#FFA75A"
bright_blue = "#85BCFF"
bright_magenta = "#AE9EFF"
bright_cyan = "#AFDBFD"
bright_white = "#E7EAEE"
