[[themes]]
name = "Teide Light"
[themes.palette]
background = "#e1e6eb"
foreground = "#6172b0"
black = "#a1a6c5"
red = "#f62466"
green = "#00663d"
yellow = "#655600"
blue = "#007496"
magenta = "#be00a2"
cyan = "#006b77"
white = "${white}"
bright_black = "#d4dbe4"
bright_red = "#ca1e47"
bright_green = "#376659"
bright_yellow = "#b55e00"
bright_blue = "#0074ba"
bright_magenta = "#8059ff"
bright_cyan = "#13658a"
bright_white = "#4c545d"
