[[themes]]
name = "Teide Dark"
[themes.palette]
background = "#161a1e"
foreground = "#a9b1d6"
black = "#414868"
red = "#F97791"
green = "#38FFA5"
yellow = "#FFE77A"
blue = "#5CCEFF"
magenta = "#FFB3EC"
cyan = "#0AE7FF"
white = "#a9b1d6"
bright_black = "#1D2228"
bright_red = "#F73F64"
bright_green = "#8FEBD3"
bright_yellow = "#FFA064"
bright_blue = "#89BEFF"
bright_magenta = "#B2A3FF"
bright_cyan = "#AFDBFD"
bright_white = "#E7EAEE"
