[[themes]]
name = "Teide Light"
[themes.palette]
background = "#d8dfe7"
foreground = "#6172b0"
black = "#a1a6c5"
red = "#f62466"
green = "#00663d"
yellow = "#615724"
blue = "#007496"
magenta = "#bb00a0"
cyan = "#006b77"
white = "#6172b0"
bright_black = "#c9d2dd"
bright_red = "#c81d47"
bright_green = "#3a6459"
bright_yellow = "#ae5d00"
bright_blue = "#0074ba"
bright_magenta = "#7e58ff"
bright_cyan = "#13658a"
bright_white = "#4c545d"
