attribute = { fg = "#ffb3ec" }
comment = { fg = "#586172", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#68c9c9" }
constant = { fg = "#8febd3" }
"constant.builtin" = { fg = "#38ffa5" }
"constant.builtin.boolean" = { fg = "#38ffa5" }
"constant.character" = { fg = "#38ffa5" }
"constant.character.escape" = { fg = "#ffb3ec" }
"constant.numeric" = { fg = "#38ffa5" }
"constant.numeric.float" = { fg = "#38ffa5" }
"constant.numeric.integer" = { fg = "#38ffa5" }
constructor = { fg = "#ffcb77" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { bg = "#1e252e", fg = "#2aa9df" }
"diff.delta.moved" = { fg = "#5cceff" }
"diff.minus" = { bg = "#542937", fg = "#ee4b6b" }
"diff.plus" = { bg = "#2e474b", fg = "#1bb16e" }
error = { fg = "#f73f64" }
function = { fg = "#5cceff" }
"function.builtin" = { fg = "#5cceff" }
"function.macro" = { fg = "#ffb3ec" }
"function.method" = { fg = "#5cceff" }
"function.special" = { fg = "#ffb3ec" }
hint = { fg = "#41ffdc" }
info = { fg = "#0ae7ff" }
keyword = { fg = "#f97791", modifiers = ["italic"] }
"keyword.control" = { fg = "#b1a2ff" }
"keyword.control.conditional" = { fg = "#b1a2ff" }
"keyword.control.exception" = { fg = "#b1a2ff" }
"keyword.control.repeat" = { fg = "#b1a2ff" }
"keyword.control.return" = { fg = "#f97791" }
"keyword.directive" = { fg = "#ffb3ec" }
"keyword.function" = { fg = "#f97791" }
"keyword.operator" = { fg = "#b1a2ff" }
label = { fg = "#5cceff" }
"markup.bold" = { fg = "#e7eaee", modifiers = ["bold"] }
"markup.heading" = { fg = "#5cceff", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#161a1e", fg = "#e7eaee" }
"markup.heading.hover" = { bg = "#3f4552" }
"markup.italic" = { fg = "#e7eaee", modifiers = ["italic"] }
"markup.link" = { fg = "#41ffdc" }
"markup.link.label" = { fg = "#ffa064" }
"markup.link.text" = { fg = "#41ffdc" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#00648f" }
"markup.normal.completion" = { fg = "#586172" }
"markup.normal.hover" = { fg = "#a9b1d6" }
"markup.raw" = { fg = "#38ffa5" }
"markup.raw.inline" = { bg = "#414868", fg = "#5cceff" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#5cceff" }
operator = { fg = "#ffb3ec" }
special = { fg = "#ffa064" }
string = { fg = "#38ffa5" }
"string.regexp" = { fg = "#8febd3" }
"string.special" = { fg = "#ffa064" }
tag = { fg = "#b1a2ff" }
type = { fg = "#ffcb77" }
"type.builtin" = { fg = "#ffcb77" }
"type.enum" = { fg = "#ffcb77" }
"type.enum.variant" = { fg = "#8febd3" }
"ui.background" = { bg = "bg" }
"ui.bufferline.active" = { bg = "bg_visual", fg = "fg" }
"ui.cursor" = { bg = "#e7eaee", fg = "#1d2228" }
"ui.cursor.match" = { fg = "#ff924e", modifiers = ["bold"] }
"ui.linenr" = { fg = "#474e5c" }
"ui.linenr.select" = { fg = "#ff924e", modifiers = ["bold"] }
"ui.menu" = { bg = "#161a1e", fg = "#e7eaee" }
"ui.menu.scroll" = { bg = 2106408, fg = 4673116 }
"ui.menu.selected" = { bg = "#3f4552" }
"ui.popup" = { bg = "#13161a", fg = "#739fd4" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#161a1e", fg = "#a9b1d6" }
"ui.statusline.inactive" = { bg = "#161a1e", fg = "#474e5c" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#1d2228", fg = "#e7eaee" }
"ui.text.focus" = { bg = "#33394a" }
"ui.text.inactive" = { fg = "#586172", modifiers = ["italic"] }
"ui.text.info" = { bg = "#13161a", fg = "#e7eaee" }
"ui.virtual.inlay-hint" = { bg = "#21383a", fg = "#41ffdc" }
"ui.window" = { fg = "#171b20", modifiers = ["bold"] }
variable = { fg = "#e7eaee" }
"variable.builtin" = { fg = "#41ffdc" }
"variable.other.member" = { fg = "#bfc7d1" }
"variable.parameter" = { fg = "#afdbfd" }
warning = { fg = "#ffe77a" }

[palette]
bg = "#1D2228"
bg_dark = "#161a1e"
bg_darker = "#13161a"
bg_dimmed = "#191d22"
bg_float = "#13161a"
bg_highlight = "#2C313A"
bg_popup = "#161a1e"
bg_search = "#00648F"
bg_sidebar = "#161a1e"
bg_statusline = "#161a1e"
bg_visual = "#33394a"
black = "#171b20"
blue = "#5CCEFF"
blue0 = "#00648F"
blue1 = "#89BEFF"
blue2 = "#9DA9E7"
blue5 = "#AFDBFD"
blue6 = "#AFDBFD"
blue7 = "#254365"
border = "#171b20"
border_highlight = "#739fd4"
comment = "#586172"
cyan = "#0AE7FF"
cyan2 = "#00FBFF"
dark3 = "#545c7e"
dark5 = "#B9B8D3"
dark6 = "#8E98A8"
dark7 = "#BFC7D1"
"diff.add" = "#2e474b"
"diff.change" = "#1e252e"
"diff.delete" = "#542937"
"diff.text" = "#254365"
error = "#F73F64"
fg = "#E7EAEE"
fg_dark = "#a9b1d6"
fg_darker = "#919BCA"
fg_float = "#E7EAEE"
fg_gutter = "#474E5C"
fg_sidebar = "#a9b1d6"
fg_sidebar_inactive = "#919BCA"
"git.add" = "#1BB16E"
"git.change" = "#2AA9DF"
"git.delete" = "#EE4B6B"
"git.ignore" = "#545c7e"
green = "#38FFA5"
green1 = "#8FEBD3"
green2 = "#68C9C9"
hint = "#41FFDC"
info = "#0AE7FF"
magenta = "#FFB3EC"
magenta2 = "#B1A2FF"
orange = "#FFA064"
orange1 = "#FF924E"
purple = "#F7D96C"
rainbow = "#38FFA5"
"rainbow.2" = "#5CCEFF"
"rainbow.3" = "#B1A2FF"
"rainbow.4" = "#FFE77A"
"rainbow.5" = "#F97791"
"rainbow.6" = "#41FFDC"
"rainbow.7" = "#F7D96C"
"rainbow.8" = "#FFA064"
red = "#F97791"
red1 = "#F73F64"
teal = "#41FFDC"
"terminal.black" = "#171b20"
"terminal.black_bright" = "#414868"
"terminal.blue" = "#5CCEFF"
"terminal.blue_bright" = "#89BEFF"
"terminal.cyan" = "#0AE7FF"
"terminal.cyan_bright" = "#00FBFF"
"terminal.green" = "#38FFA5"
"terminal.green_bright" = "#41FFDC"
"terminal.magenta" = "#B1A2FF"
"terminal.magenta_bright" = "#FFB3EC"
"terminal.red" = "#F97791"
"terminal.red_bright" = "#F73F64"
"terminal.white" = "#a9b1d6"
"terminal.white_bright" = "#E7EAEE"
"terminal.yellow" = "#FFA064"
"terminal.yellow_bright" = "#FFE77A"
terminal_black = "#414868"
todo = "#5CCEFF"
warning = "#FFE77A"
yellow = "#FFE77A"
yellow1 = "#FFCB77"