attribute = { fg = "#bb00a0" }
comment = { fg = "#828fa7", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#3c7a7a" }
constant = { fg = "#3a6459" }
"constant.builtin" = { fg = "#00663d" }
"constant.builtin.boolean" = { fg = "#00663d" }
"constant.character" = { fg = "#00663d" }
"constant.character.escape" = { fg = "#bb00a0" }
"constant.numeric" = { fg = "#00663d" }
"constant.numeric.float" = { fg = "#00663d" }
"constant.numeric.integer" = { fg = "#00663d" }
constructor = { fg = "#7d5a00" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { bg = "#cdd7e5", fg = "#218bb9" }
"diff.delta.moved" = { fg = "#007496" }
"diff.minus" = { bg = "#d1acbd", fg = "#c02d4d" }
"diff.plus" = { bg = "#b3c6cd", fg = "#15975d" }
error = { fg = "#c81d47" }
function = { fg = "#007496" }
"function.builtin" = { fg = "#007496" }
"function.macro" = { fg = "#bb00a0" }
"function.method" = { fg = "#007496" }
"function.special" = { fg = "#bb00a0" }
hint = { fg = "#006252" }
info = { fg = "#006b77" }
keyword = { fg = "#f62466", modifiers = ["italic"] }
"keyword.control" = { fg = "#7e58ff" }
"keyword.control.conditional" = { fg = "#7e58ff" }
"keyword.control.exception" = { fg = "#7e58ff" }
"keyword.control.repeat" = { fg = "#7e58ff" }
"keyword.control.return" = { fg = "#f62466" }
"keyword.directive" = { fg = "#bb00a0" }
"keyword.function" = { fg = "#f62466" }
"keyword.operator" = { fg = "#7e58ff" }
label = { fg = "#007496" }
"markup.bold" = { fg = "#4c545d", modifiers = ["bold"] }
"markup.heading" = { fg = "#007496", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#e1e6eb", fg = "#4c545d" }
"markup.heading.hover" = { bg = "#a5aec1" }
"markup.italic" = { fg = "#4c545d", modifiers = ["italic"] }
"markup.link" = { fg = "#006252" }
"markup.link.label" = { fg = "#ae5d00" }
"markup.link.text" = { fg = "#006252" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#009bda" }
"markup.normal.completion" = { fg = "#828fa7" }
"markup.normal.hover" = { fg = "#6172b0" }
"markup.raw" = { fg = "#00663d" }
"markup.raw.inline" = { bg = "#a1a6c5", fg = "#007496" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#007496" }
operator = { fg = "#bb00a0" }
special = { fg = "#ae5d00" }
string = { fg = "#00663d" }
"string.regexp" = { fg = "#3a6459" }
"string.special" = { fg = "#ae5d00" }
tag = { fg = "#7e58ff" }
type = { fg = "#7d5a00" }
"type.builtin" = { fg = "#7d5a00" }
"type.enum" = { fg = "#7d5a00" }
"type.enum.variant" = { fg = "#3a6459" }
"ui.background" = { bg = "bg" }
"ui.bufferline.active" = { bg = "bg_visual", fg = "fg" }
"ui.cursor" = { bg = "#4c545d", fg = "#d4dbe4" }
"ui.cursor.match" = { fg = "#bb5e00", modifiers = ["bold"] }
"ui.linenr" = { fg = "#99a3b8" }
"ui.linenr.select" = { fg = "#bb5e00", modifiers = ["bold"] }
"ui.menu" = { bg = "#e1e6eb", fg = "#4c545d" }
"ui.menu.scroll" = { bg = 14344164, fg = 10068920 }
"ui.menu.selected" = { bg = "#a5aec1" }
"ui.popup" = { bg = "#e8ebef", fg = "#2a89c2" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#e1e6eb", fg = "#6172b0" }
"ui.statusline.inactive" = { bg = "#e1e6eb", fg = "#99a3b8" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#d4dbe4", fg = "#4c545d" }
"ui.text.focus" = { bg = "#b6bdd0" }
"ui.text.inactive" = { fg = "#828fa7", modifiers = ["italic"] }
"ui.text.info" = { bg = "#e8ebef", fg = "#4c545d" }
"ui.virtual.inlay-hint" = { bg = "#bfcfd5", fg = "#006252" }
"ui.window" = { fg = "#aaafb6", modifiers = ["bold"] }
variable = { fg = "#4c545d" }
"variable.builtin" = { fg = "#006252" }
"variable.other.member" = { fg = "#606974" }
"variable.parameter" = { fg = "#13658a" }
warning = { fg = "#615400" }

[palette]
bg = "#d4dbe4"
bg_dark = "#e1e6eb"
bg_darker = "#e8ebef"
bg_dimmed = "#dde1e8"
bg_float = "#e8ebef"
bg_highlight = "#c0c6d3"
bg_popup = "#e1e6eb"
bg_search = "#009bda"
bg_sidebar = "#e1e6eb"
bg_statusline = "#e1e6eb"
bg_visual = "#b6bdd0"
black = "#aaafb6"
blue = "#007496"
blue0 = "#009bda"
blue1 = "#0074ba"
blue2 = "#5873d5"
blue5 = "#13658a"
blue6 = "#13658a"
blue7 = "#8db4ea"
border = "#aaafb6"
border_highlight = "#2a89c2"
comment = "#828fa7"
cyan = "#006b77"
cyan2 = "#006263"
dark3 = "#8990b3"
dark5 = "#6c6aa0"
dark6 = "#7e8796"
dark7 = "#606974"
"diff.add" = "#b3c6cd"
"diff.change" = "#cdd7e5"
"diff.delete" = "#d1acbd"
"diff.text" = "#8db4ea"
error = "#c81d47"
fg = "#4c545d"
fg_dark = "#6172b0"
fg_darker = "#7280ba"
fg_float = "#4c545d"
fg_gutter = "#99a3b8"
fg_sidebar = "#6172b0"
fg_sidebar_inactive = "#7280ba"
"git.add" = "#15975d"
"git.change" = "#218bb9"
"git.delete" = "#c02d4d"
"git.ignore" = "#8990b3"
green = "#00663d"
green1 = "#3a6459"
green2 = "#3c7a7a"
hint = "#006252"
info = "#006b77"
magenta = "#bb00a0"
magenta2 = "#7e58ff"
orange = "#ae5d00"
orange1 = "#bb5e00"
purple = "#695b29"
rainbow = "#00663d"
"rainbow.2" = "#007496"
"rainbow.3" = "#7e58ff"
"rainbow.4" = "#615400"
"rainbow.5" = "#f62466"
"rainbow.6" = "#006252"
"rainbow.7" = "#695b29"
"rainbow.8" = "#ae5d00"
red = "#f62466"
red1 = "#c81d47"
teal = "#006252"
"terminal.black" = "#aaafb6"
"terminal.black_bright" = "#a1a6c5"
"terminal.blue" = "#007496"
"terminal.blue_bright" = "#0074ba"
"terminal.cyan" = "#006b77"
"terminal.cyan_bright" = "#006263"
"terminal.green" = "#00663d"
"terminal.green_bright" = "#006252"
"terminal.magenta" = "#7e58ff"
"terminal.magenta_bright" = "#bb00a0"
"terminal.red" = "#f62466"
"terminal.red_bright" = "#c81d47"
"terminal.white" = "#6172b0"
"terminal.white_bright" = "#4c545d"
"terminal.yellow" = "#ae5d00"
"terminal.yellow_bright" = "#615400"
terminal_black = "#a1a6c5"
todo = "#007496"
warning = "#615400"
yellow = "#615400"
yellow1 = "#7d5a00"