[mgr]
# NOTE: can be combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#6172b0", italic = true }

# Hovered
hovered         = { bg = "#c0c6d3" }
preview_hovered = { bg = "#c0c6d3" }

# Find
find_keyword  = { fg = "#d8dfe7", bg = "#ae5d00", bold = true }
find_position = { fg = "#006b77", bg = "#b5c8d3", bold = true }

# Marker
marker_copied   = { fg = "#00663d", bg = "#00663d" }
marker_cut      = { fg = "#f62466", bg = "#f62466" }
marker_marked   = { fg = "#bb00a0", bg = "#bb00a0" }
marker_selected = { fg = "#007496", bg = "#007496" }

# Count
count_copied   = { fg = "#d8dfe7", bg = "#00663d" }
count_cut      = { fg = "#d8dfe7", bg = "#f62466" }
count_selected = { fg = "#d8dfe7", bg = "#007496" }

# Border
border_symbol = "│"
border_style  = { fg = "#2887c1" }

# Tab
[tabs]
active   = { fg = "#a1a8b1", bg = "#007496" }
inactive = { fg = "#007496", bg = "#99a3b8" }

[mode]
normal_main = { fg = "#a1a8b1", bg = "#007496", bold = true }
normal_alt  = { fg = "#007496", bg = "#99a3b8" }

select_main = { fg = "#a1a8b1", bg = "#bb00a0", bold = true }
select_alt  = { fg = "#bb00a0", bg = "#99a3b8" }

unset_main  = { fg = "#a1a8b1", bg = "#695b29", bold = true }
unset_alt   = { fg = "#695b29", bg = "#99a3b8" }

[status]
overall   = { fg = "#4c545d", bg = "#d8dfe7" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#4c545d", bold = true }
progress_normal = { fg = "#009bda", bg = "#c0c6d3" }
progress_error  = { fg = "#c81d47", bg = "#c0c6d3" }

# Permissions
perm_type  = { fg = "#007496" }
perm_read  = { fg = "#615724" }
perm_write = { fg = "#f62466" }
perm_exec  = { fg = "#00663d" }
perm_sep   = { fg = "#a1a6c5" }

[pick]
border   = { fg = "#2887c1" }
active   = { fg = "#4c545d",  bg = "#afb8cc" }
inactive = { fg = "#4c545d" }

# Input
[input]
border   = { fg = "#5873d5" }
title    = { fg = "#5873d5" }
value    = { fg = "#695b29" }
selected = { bg = "#afb8cc" }

# Completion
[cmp]
border   = { fg = "#5873d5" }
active   = { fg = "#4c545d", bg = "#a3acbf" }
inactive = { fg = "#4c545d" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#2887c1" }
title   = { fg = "#2887c1" }
hovered = { fg = "#4c545d", bg = "#afb8cc" }

# Which
[which]
cols            = 3
mask            = { bg = "#d8dfe7" }
cand            = { fg = "#006b77" }
rest            = { fg = "#007496" }
desc            = { fg = "#bb00a0" }
separator       = " ➜ "
separator_style = { fg = "#828fa7" }

# Confirm
[confirm]
border  = { fg = "#5873d5" }
title   = { fg = "#2887c1" }
content = {}
list    = {}
btn_yes = { bg = "#afb8cc" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#2887c1" }
title   = { fg = "#2887c1" }

# Notify
[notify]
title_info  = { fg = "#006b77" }
title_warn  = { fg = "#615724" }
title_error = { fg = "#c81d47" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#00663d" }
run     = { fg = "#bb00a0" }
desc    = { fg = "#006b77" }
hovered = { bg = "#c0c6d3" }
footer  = { fg = "#4c545d", bg = "#c9d2dd" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#615724" },

	# Media
	{ mime = "{audio,video}/*", fg = "#bb00a0" },

	# Archives
	{ mime = "application/*zip", fg = "#f62466" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f62466" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#006b77" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#f62466" },

	# Special files
	{ name = "*", is = "orphan", bg = "#f62466" },
	{ name = "*", is = "exec"  , fg = "#00663d" },

	# Fallback
	{ name = "*/", fg = "#007496" },
	{ name = "*", fg = "#4c545d" }
]
    