[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#6172b0", italic = true }

# Hovered
hovered         = { bg = "#c0c6d3" }
preview_hovered = { bg = "#c0c6d3" }

# Find
find_keyword  = { fg = "#e1e6eb", bg = "#b55e00", bold = true }
find_position = { fg = "#5873d5", bg = "#bfd0d9", bold = true }

# Marker
marker_copied   = { fg = "#376659", bg = "#376659" }
marker_cut      = { fg = "#f62466", bg = "#f62466" }
marker_marked   = { fg = "#be00a2", bg = "#be00a2" }
marker_selected = { fg = "#007496", bg = "#007496" }

# Tab
tab_active   = { fg = "#4c545d", bg = "#c0c6d3" }
tab_inactive = { fg = "#99a3b8", bg = "#d4dbe4" }
tab_width    = 1

# Count
count_copied   = { fg = "#4c545d", bg = "#3c7a7a" }
count_cut      = { fg = "#4c545d", bg = "#ca1e47" }
count_selected = { fg = "#4c545d", bg = "#009bda" }

# Border
border_symbol = "│"
border_style  = { fg = "#2a89c2" }

[mode]
normal_main = { fg = "#aaafb6", bg = "#007496", bold = true }
normal_alt  = { fg = "#007496", bg = "#99a3b8" }

select_main = { fg = "#aaafb6", bg = "#be00a2", bold = true }
select_alt  = { fg = "#be00a2", bg = "#99a3b8" }

unset_main  = { fg = "#aaafb6", bg = "#695b29", bold = true }
unset_alt   = { fg = "#695b29", bg = "#99a3b8" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#99a3b8", bg = "#99a3b8" }

# Progress
progress_label  = { fg = "#6172b0", bold = true }
progress_normal = { fg = "#d4dbe4" }
progress_error  = { fg = "#f62466" }

# Permissions
perm_type  = { fg = "#007496" }
perm_read  = { fg = "#655600" }
perm_write = { fg = "#f62466" }
perm_exec  = { fg = "#00663d" }
perm_sep   = { fg = "#a1a6c5" }

[pick]
border   = { fg = "#2a89c2" }
active   = { fg = "#4c545d",  bg = "#b6bdd0" }
inactive = { fg = "#4c545d" }

# Input
[input]
border   = { fg = "#5873d5" }
title    = { fg = "#5873d5" }
value    = { fg = "#695b29" }
selected = { bg = "#b6bdd0" }

# Completion
[completion]
border   = { fg = "#5873d5" }
active   = { fg = "#4c545d", bg = "#b6bdd0" }
inactive = { fg = "#4c545d" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#2a89c2" }
title   = { fg = "#2a89c2" }
hovered = { fg = "#4c545d", bg="#b6bdd0" }

# Which
[which]
cols            = 3
mask            = { bg = "#e1e6eb" }
cand            = { fg = "#006b77" }
rest            = { fg = "#007496" }
desc            = { fg = "#be00a2" }
separator       = " ➜ "
separator_style = { fg = "#828fa7" }

# Confirm
[confirm]
border  = { fg = "#5873d5" }
title   = { fg = "#2a89c2" }
content = {}
list    = {}
btn_yes = { bg = "#b6bdd0" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#2a89c2" }
title   = { fg = "#2a89c2" }

# Notify
[notify]
title_info  = { fg = "#006b77" }
title_warn  = { fg = "#655600" }
title_error = { fg = "#ca1e47" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#00663d" }
run     = { fg = "#be00a2" }
hovered = { bg = "#c0c6d3" }
footer  = { fg = "#4c545d", bg = "#d4dbe4" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#655600" },

	# Media
	{ mime = "{audio,video}/*", fg = "#be00a2" },

	# Archives
	{ mime = "application/*zip", fg = "#f62466" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f62466" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#006b77" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#f62466" },

	# Special files
	{ name = "*", is = "orphan", bg = "#f62466" },
	{ name = "*", is = "exec"  , fg = "#00663d" },

	# Fallback
	{ name = "*/", fg = "#007496" }
]
    